name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master  # ou main selon ton repo
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3

      - name: Upload artifact for static site
        uses: actions/upload-artifact@v3
        with:
          name: static-site
          path: .

      - name: Azure Static Web Apps Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_XXXX }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "."       # Tes fichiers sont à la racine
          output_location: "."    # Pas de build, donc la sortie est aussi la racine
